
name: .NET Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.202
      - name: Build for Linux
        run: dotnet publish -r linux-x64 --configuration Release
      - name: Build for Windows
        run: dotnet publish -r win-x64 --configuration Release
      - name: tonybogdanov-zip
        uses: TonyBogdanov/zip@1.0
      - name: Zip Linux
        run: cd ./mangadex-sharp-scraper/bin/Release/net5.0/linux-x64 && zip -qq -r ./linux-release.zip ./publish
      - name: Zip Windows
        run: cd .. && dir && zip -qq -r ./windows-release.zip ./publish
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-release
          path: linux-release.zip
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: windows-release.zip
